### PR TITLE
Added EASTL and MSVS debug options for Debugger-start development

### PR DESCRIPTION
**Pull request by dartfnm**
I want to try to add a debugger to Quaesar, with something similar to the interface like https://github.com/EpicGamesExt/raddebugger
https://github.com/wolfpld/tracy
https://github.com/WerWolv/ImHex
https://remedybg.itch.io/remedybg

So for now I added EASTL as a proven cross-platform library that extends STL and makes development safer than using C code style.

### CODE REVIEW

**Comment by emoon** [comment]
Hi, Thanks for this PR.

1. The problem is that include lots of conflicts. Please resolve all of those first before I will have a look at it.
2. I really don't like the EASTL dependency. If you really need to use STL consider using the standard library instead.

Once these above changes has been made it would be possible to take a look at the PR because now its kind of a mess

**Comment by dartfnm** [comment]
Yes of course, thanks for the quick reply.
Most of the conflicts are due to the `developer-start` branch lagging behind the `master` branch.
I would be very appreciated if you could synchronise the main branch with `developer-start` first, then I think all conflicts will be resolved by themselves.
Because I first merged these two branches myself, but github now considers them as PR. And in the future it will be hard to move this branch into `main`.

**Comment by emoon** [comment]
Right, the reason I didn't want to merge it into main yet is because it's not really usable yet. I'm not sure how far your changes takes? (it's a bit hard to get that from the diff)

**Comment by dartfnm** [comment]
> I really don't like the EASTL dependency. If you really need to use STL consider using the standard library instead.

Too bad, why don't you like EASTL ?
From my experience, it avoids problems with different STL/compiler versions, for example between gcc/clang/vc15 (as we had with SDL2). 
And it is also optimised for speed, memory and very easy to connect, because 90% of it consists of simple headers.
It has non-standard but cache-friendlier containers like `vector_map`, `fixed_vector` and `fixed_function`.

**Comment by emoon** [comment]
Ok, lets keep EASTL for now (at least it's not boost)

**Comment by dartfnm** [comment]
> Right, the reason I didn't want to merge it into main yet is because it's not really usable yet. I'm not sure how far your changes takes? (it's a bit hard to get that from the diff)

No, we don't need to merge it into `main` yet. 
It's the opposite, you just need to update the `debugger-start` branch to the current state as it in `main` now.
Because we have:
> This branch is [30 commits ahead of](https://github.com/theblacklotus/quaesar/compare/main...debugger-start), [7 commits behind](https://github.com/theblacklotus/quaesar/compare/debugger-start...main) main.

**Comment by emoon** [comment]
Ah yes! Not enough coffee today :D 

Alright, doing a merge of main to `debugger-start` makes sense before landing the above makes sense to me. I'm currently a bit short of on time, but would you be willing to try to do the merge first? Otherwise I can try to get around to it during the weekend.

**Comment by emoon** [comment]
Also thanks for taking a look at this. I have lots of ideas in this area and having a great builtin debugger will be very useful.

**Comment by emoon** [comment]
Ok, I have merged main to debugger-start branch and also enabled the CI on this branch. If you update your branch again it should (hopefully) merge easier.

**Pull request closed without merging**
